### ISSUE TITLE
Deploy Greeter from image

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/guru-night#6]
Add the text "quay.io/rhdevelopers/knative-tutorial-greeter" so that it is copy & pasteable and mention that the small magnifying glass must be clicked to show the rest of the fields.
https://www.screencast.com/t/0KVoFrjGUXP

**Comment by kameshsampath** [comment]
closed via #https://github.com/redhat-developer-demos/openshift-basics/commit/3e1b5a0d066106089409c0ca04a928aba4435f8f
